# cleaning and preprocessing
drop:
  train:
    - cycle
    - pa
  test:
    - cycle

# feature computation
velocity:
  absolute: True
rolling:
  type: null
  sizes:
    - 10
    - 25
    - 50
    - 100

# dataset split
train_val_split:
  random_state: 1337
  test_size: 0.25

# model arguments
ridge:
  alpha: 10
mlp:
  activation: relu
  hidden_layer_sizes:
    - 2000
    - 1000
    - 1000
    - 600
  solver: adam
  learning_rate: adaptive
  learning_rate_init: 0.0003
  max_iter: 1000
  verbose: True

# feature selection
selection:
  minimal:
    - clean
    - velocity:
        - vel_abs
    - rolling:
        - roll_100_std
  neural:
    - clean
    - log
    - sqrt
    - velocity
    - rolling
