# cleaning and preprocessing
drop:
  train:
    - cycle
    - pa
  test:
    - cycle

# feature computation
velocity:
  absolute: True
rolling:
  type: null
  sizes:
    - 10
    - 25
    - 50
    - 100

# dataset split
train_val_split:
  random_state: 1337
  test_size: 0.25

# model arguments
ridge:
  alpha: 10

# feature selection
selection:
  minimal:
    - clean:
        - phi
        - acc
    - velocity:
        - vel_abs
    - rolling:
        - roll_100_std
