# cleaning and preprocessing
drop:
  train:
    - cycle
    - pa
  test:
    - cycle

# feature computation
velocity:
  absolute: True
rolling:
  type: null
  sizes:
    - 10
    - 25
    - 50

# feature selection
selection:
  minimal1700:
    - clean
    - velocity
    - rolling
