name: ldc2021
channels:
  - defaults
dependencies:
  - python~=3.8
  - pip
  - black
  - flake8
  - isort
  - jupyter
  - jupyterlab
  - ipywidgets
  - numpy>=1.19
  - scipy>=1.6
  - pandas>=1.3
  - matplotlib>=3
  - scikit-learn>=0.24
  - conda-forge::kedro==0.17.4
  - conda-forge::cudatoolkit~=11.1
  - pytorch::pytorch~=1.9
  - pip:
      - funcy
      - kedro[pandas]
